title: Elysium RP
url: https://lulucorne.github.io/ElysiumRP/
baseurl: ''

collections:
  characters:
    output: true
    permalink: /characters/:name/

defaults:
  - scope:
      path: ''
      type: characters
    values:
      layout: character
